/**
 * Vendored copy of `@windy/control-panel-protocols` for use by account-server's
 * Vitals + Fleet endpoints (WD-31 M-D; ADR-054).
 *
 * Source of truth: the JSON Schemas at
 *   sneakyfree/windy-control-panel/packages/protocols/schemas/
 * The Zod definitions below were generated by that package's codegen.mjs
 * and copy-pasted here verbatim so account-server doesn't need an npm
 * publish step or a cross-repo file: dep (windy-pro's deploy is
 * self-contained under /opt/windy-pro/deploy-prod/).
 *
 * The companion drift-guard at
 *   tests/control-panel-schema-drift.test.ts
 * fails if the vendored JSON Schemas have drifted from the canonical
 * copies when both repos are checked out side-by-side. CI doesn't depend
 * on the canonical repo being present; the test no-ops when it isn't.
 *
 * If the canonical schemas evolve (v1.x additive change), re-vendor by:
 *   1. cp ~/windy-control-panel/packages/protocols/schemas/*.json
 *      src/contracts/control-panel/
 *   2. Replace the Zod literals in this file with the new generated
 *      output from ~/windy-control-panel/packages/protocols/dist/index.js.
 *   3. Re-run jest — the drift guard + route tests will catch breakage.
 */

import { z } from 'zod';

// ─── Vitals v1 ─────────────────────────────────────────────────────

export const VitalsV1Schema = z
    .object({
        schema: z.literal('windy.vitals.v1'),
        sampled_at: z.string().datetime({ offset: true }),
        source: z.enum([
            'electron-local',
            'agent-vps',
            'account-server',
            'mobile',
            'cloud-aggregator',
        ]),
        host: z
            .object({
                hostname: z.string().min(1),
                model: z.union([z.string(), z.null()]),
                platform: z.enum([
                    'darwin',
                    'linux',
                    'win32',
                    'ios',
                    'android',
                    'unknown',
                ]),
                release: z.string(),
                arch: z.string(),
                ip: z.union([z.string(), z.null()]),
                uptime_seconds: z.number().gte(0),
                location: z.union([
                    z.null(),
                    z.object({
                        city: z.string(),
                        region: z.string(),
                        country: z.string(),
                    }).strict(),
                ]),
            })
            .strict(),
        cpu: z
            .object({
                model: z.string(),
                cores: z.number().int().gte(1),
                avg_utilization_pct: z.number().gte(0).lte(100),
                core_utilization_pct: z.array(z.number().gte(0).lte(100)),
                temperature_c: z.union([z.number(), z.null()]),
            })
            .strict(),
        gpu: z.union([
            z.null(),
            z.object({
                model: z.string(),
                memory_total_bytes: z.number().int().gte(0),
                memory_used_bytes: z.number().int().gte(0),
                utilization_pct: z.number().gte(0).lte(100),
                temperature_c: z.union([z.number(), z.null()]),
            }).strict(),
        ]),
        memory: z
            .object({
                total_bytes: z.number().int().gte(0),
                available_bytes: z.number().int().gte(0),
                used_pct: z.number().gte(0).lte(100),
            })
            .strict(),
        disk: z
            .object({
                total_bytes: z.number().int().gte(0),
                used_bytes: z.number().int().gte(0),
                used_pct: z.number().gte(0).lte(100),
            })
            .strict(),
        network: z
            .object({
                total_tx_bytes_per_sec: z.number().gte(0),
                total_rx_bytes_per_sec: z.number().gte(0),
            })
            .strict(),
        load: z.array(z.number().gte(0)).min(3).max(3),
        processes: z
            .object({
                all: z.number().int().gte(0),
                running: z.union([z.null(), z.number().int().gte(0)]),
                sleeping: z.union([z.null(), z.number().int().gte(0)]),
            })
            .strict(),
        thermal: z.union([
            z.null(),
            z.object({
                state: z.enum(['ok', 'fair', 'serious', 'critical']),
                temperature_c: z.union([z.number(), z.null()]),
            }).strict(),
        ]),
    })
    .strict();

export type VitalsV1 = z.infer<typeof VitalsV1Schema>;

// ─── Fleet v1 ──────────────────────────────────────────────────────

export const FleetV1Schema = z
    .object({
        schema: z.literal('windy.fleet.v1'),
        fetched_at: z.string().datetime({ offset: true }),
        user_id: z.string().min(1),
        this_machine: z
            .object({
                is_user_device: z.boolean(),
                can_self_report: z.boolean(),
                vitals_url: z.union([z.string(), z.null()]),
            })
            .strict(),
        agents: z.array(
            z
                .object({
                    id: z.string().min(1),
                    name: z.string().min(1),
                    callsign: z.union([z.string(), z.null()]),
                    product: z.string().min(1),
                    status: z.enum(['online', 'offline', 'unknown']),
                    machine: z
                        .object({
                            model: z.string(),
                            location: z.union([
                                z.null(),
                                z.object({
                                    city: z.string(),
                                    region: z.string(),
                                    country: z.string(),
                                }).strict(),
                            ]),
                        })
                        .strict(),
                    vitals_url: z.string().min(1),
                    auth: z.enum(['cf-access', 'bearer', 'none']),
                    created_at: z.string().datetime({ offset: true }),
                    last_heartbeat: z.string().datetime({ offset: true }),
                })
                .strict(),
        ),
    })
    .strict();

export type FleetV1 = z.infer<typeof FleetV1Schema>;

// ─── Constants ─────────────────────────────────────────────────────

export const VITALS_V1_SCHEMA_ID = 'windy.vitals.v1' as const;
export const FLEET_V1_SCHEMA_ID = 'windy.fleet.v1' as const;

export const VITALS_SOURCES = [
    'electron-local',
    'agent-vps',
    'account-server',
    'mobile',
    'cloud-aggregator',
] as const;
export type VitalsSource = (typeof VITALS_SOURCES)[number];

export const HOST_PLATFORMS = [
    'darwin',
    'linux',
    'win32',
    'ios',
    'android',
    'unknown',
] as const;
export type HostPlatform = (typeof HOST_PLATFORMS)[number];

export const AGENT_STATUSES = ['online', 'offline', 'unknown'] as const;
export type AgentStatus = (typeof AGENT_STATUSES)[number];

export const AGENT_AUTH_TYPES = ['cf-access', 'bearer', 'none'] as const;
export type AgentAuth = (typeof AGENT_AUTH_TYPES)[number];

export const THERMAL_STATES = ['ok', 'fair', 'serious', 'critical'] as const;
export type ThermalState = (typeof THERMAL_STATES)[number];

// ─── Helpers ───────────────────────────────────────────────────────

export type ValidationResult<T> =
    | { valid: true; data: T }
    | { valid: false; errors: z.ZodIssue[] };

export function validateVitals(payload: unknown): ValidationResult<VitalsV1> {
    const result = VitalsV1Schema.safeParse(payload);
    return result.success
        ? { valid: true, data: result.data }
        : { valid: false, errors: result.error.issues };
}

export function validateFleet(payload: unknown): ValidationResult<FleetV1> {
    const result = FleetV1Schema.safeParse(payload);
    return result.success
        ? { valid: true, data: result.data }
        : { valid: false, errors: result.error.issues };
}
