#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════
# Windy Pro — One-Shot Cloud Deploy for thewindstorm.uk
# Run this on Veron 1 with sudo access.
# ═══════════════════════════════════════════════════════
set -euo pipefail

DOMAIN="windyword.ai"
DEPLOY_DIR="/opt/windy-pro"
GREEN='\033[0;32m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════════╗"
echo "║  🌪️  Windy Pro — Cloud Deploy                    ║"
echo "║  Domain: ${DOMAIN}                       ║"
echo "╚══════════════════════════════════════════════════╝"
echo -e "${NC}"

# ───────────────────────────────────────────────────────
# 1. Check prerequisites
# ───────────────────────────────────────────────────────
echo -e "${CYAN}[1/6] Checking prerequisites...${NC}"

if ! command -v docker &>/dev/null; then
    echo -e "${RED}Docker not found. Installing...${NC}"
    curl -fsSL https://get.docker.com | sudo sh
    sudo usermod -aG docker "$USER"
    echo -e "${GREEN}Docker installed ✅${NC}"
fi

if ! docker compose version &>/dev/null; then
    echo -e "${RED}Docker Compose v2 not found. Installing...${NC}"
    sudo apt-get update && sudo apt-get install -y docker-compose-plugin
fi

echo -e "${GREEN}Docker $(docker --version | cut -d' ' -f3) ✅${NC}"

# ───────────────────────────────────────────────────────
# 2. Set up deploy directory
# ───────────────────────────────────────────────────────
echo -e "${CYAN}[2/6] Setting up ${DEPLOY_DIR}...${NC}"

sudo mkdir -p "${DEPLOY_DIR}"
sudo cp -r deploy/* "${DEPLOY_DIR}/"
sudo cp Dockerfile "${DEPLOY_DIR}/"
sudo cp requirements.txt "${DEPLOY_DIR}/"
sudo cp -r src/ "${DEPLOY_DIR}/src/"

# ───────────────────────────────────────────────────────
# 3. Generate secrets
# ───────────────────────────────────────────────────────
echo -e "${CYAN}[3/6] Generating secrets...${NC}"

if [ ! -f "${DEPLOY_DIR}/.env" ]; then
    API_KEY=$(openssl rand -hex 32)
    JWT_SECRET=$(openssl rand -hex 32)
    PG_PASS=$(openssl rand -hex 16)
    
    cat > "${DEPLOY_DIR}/.env" <<EOF
# Auto-generated by deploy.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
WINDY_API_KEY=${API_KEY}
WINDY_JWT_SECRET=${JWT_SECRET}
POSTGRES_PASSWORD=${PG_PASS}
WHISPER_MODEL=base
EOF
    echo -e "${GREEN}Secrets generated ✅${NC}"
    echo -e "  API Key: ${API_KEY:0:8}..."
    echo -e "  JWT:     ${JWT_SECRET:0:8}..."
else
    echo -e "${GREEN}Existing .env found, keeping it ✅${NC}"
fi

# ───────────────────────────────────────────────────────
# 4. SSL Certificates (Cloudflare Origin)
# ───────────────────────────────────────────────────────
echo -e "${CYAN}[4/6] Setting up SSL certificates...${NC}"

CERT_DIR="${DEPLOY_DIR}/certs"
sudo mkdir -p "${CERT_DIR}"

if [ ! -f "${CERT_DIR}/fullchain.pem" ]; then
    echo ""
    echo -e "${RED}═══════════════════════════════════════════════════${NC}"
    echo -e "${RED}  SSL CERTS NEEDED${NC}"
    echo ""
    echo "  Since ${DOMAIN} is on Cloudflare, you have two options:"
    echo ""
    echo "  Option A: Cloudflare Origin Certificate (recommended)"
    echo "    1. Go to: Cloudflare Dashboard → ${DOMAIN} → SSL/TLS → Origin Server"
    echo "    2. Click 'Create Certificate'"
    echo "    3. Save the certificate as: ${CERT_DIR}/fullchain.pem"
    echo "    4. Save the private key as:  ${CERT_DIR}/privkey.pem"
    echo "    5. In Cloudflare SSL/TLS settings, set mode to 'Full (strict)'"
    echo ""
    echo "  Option B: Let's Encrypt (requires Cloudflare proxy OFF temporarily)"
    echo "    sudo certbot certonly --standalone -d ${DOMAIN}"
    echo "    sudo cp /etc/letsencrypt/live/${DOMAIN}/fullchain.pem ${CERT_DIR}/"
    echo "    sudo cp /etc/letsencrypt/live/${DOMAIN}/privkey.pem ${CERT_DIR}/"
    echo ""
    echo -e "${RED}═══════════════════════════════════════════════════${NC}"
    echo ""
    read -p "Press Enter once you've placed the certs, or Ctrl+C to abort... "
fi

if [ -f "${CERT_DIR}/fullchain.pem" ] && [ -f "${CERT_DIR}/privkey.pem" ]; then
    echo -e "${GREEN}SSL certs found ✅${NC}"
else
    echo -e "${RED}Warning: SSL certs not found. Nginx will fail to start.${NC}"
fi

# ───────────────────────────────────────────────────────
# 5. Build and deploy web client
# ───────────────────────────────────────────────────────
echo -e "${CYAN}[5/6] Building web client...${NC}"

if command -v npm &>/dev/null; then
    cd src/client/web
    npm install --production 2>/dev/null || true
    npm run build 2>/dev/null || echo "Web build skipped (not critical)"
    if [ -d "dist" ]; then
        sudo mkdir -p "${DEPLOY_DIR}/web-dist"
        sudo cp -r dist/* "${DEPLOY_DIR}/web-dist/"
        echo -e "${GREEN}Web client built ✅${NC}"
    fi
    cd - >/dev/null
else
    echo "npm not found — skipping web client build"
fi

# ───────────────────────────────────────────────────────
# 6. Launch
# ───────────────────────────────────────────────────────
echo -e "${CYAN}[6/6] Launching Windy Pro Cloud...${NC}"

cd "${DEPLOY_DIR}"
sudo docker compose pull 2>/dev/null || true
sudo docker compose build --no-cache
sudo docker compose up -d

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  🌪️  Windy Pro Cloud — LIVE                      ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║                                                  ║${NC}"
echo -e "${GREEN}║  🌐 Web:  https://${DOMAIN}               ║${NC}"
echo -e "${GREEN}║  🔌 WS:   wss://${DOMAIN}/ws/transcribe   ║${NC}"
echo -e "${GREEN}║  ❤️  Health: https://${DOMAIN}/health      ║${NC}"
echo -e "${GREEN}║                                                  ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo "Next steps:"
echo "  1. Point ${DOMAIN} A record → this server's IP in Cloudflare"
echo "  2. Set Cloudflare SSL mode → Full (strict)"
echo "  3. Test: curl https://${DOMAIN}/health"
echo "  4. Logs: cd ${DEPLOY_DIR} && docker compose logs -f"
echo ""
